# Generated by Django 5.2.6 on 2025-09-29 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('service_type', models.CharField(choices=[('general', 'Общий клининг'), ('deep', 'Генеральная уборка'), ('post_building', 'Послестроительная уборка'), ('dry_clean', 'Химчистка ковров и мебели')], max_length=50, verbose_name='Вид услуги')),
                ('preferred_datetime', models.DateTimeField(verbose_name='Желаемая дата и время')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], max_length=20, verbose_name='Тип оплаты')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('in_progress', 'В работе'), ('done', 'Услуга оказана'), ('cancelled', 'Отменено')], default='new', max_length=20, verbose_name='Статус')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина отмены')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
